### ISSUE TITLE
Panel does not update/move when navigating a website

### ISSUE THREAD

**Issue by timmychan97** [donny-chan/MediaManipulator#9]
This happens in the following cases:
 - pressing "back" button of the browsers, when watching a video
 - pressing the theater mode, which scales and moves the video.

Steps to reproduce (1):
 - Go to youtube.com
 - Press on a video
 - Press back

Steps to reproduce (2):
 - Go to youtube.com
 - Press on a video
 - Press "theater mode"

**Comment by donny-chan** [comment]
I think this can be fixed using a MutationObserver, which might also solve the bug where a video within an iframe won't be detected.

**Comment by donny-chan** [comment]
I think it is solved by commit 2acd437

**Comment by chen-yingfa** [comment]
I think this is solved after fix #9.
